### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by diohabara** [yuichan00/NLP100#1]
- [x] `git`のインストール
- [x] `brew`のインストール
- [x] `Python`のインストール
- [x] `pyenv`のインストール
- [x] `pip`のインストール
- [x] `vscode`のインストール

**Comment by yuichan00** [comment]
`brew `
- ソフトウェアを管理するツール

**Comment by yuichan00** [comment]
PATHとは
https://qiita.com/HORIZONium/items/b608f46c900ce527dbc9

**Comment by yuichan00** [comment]
https://pip.pypa.io/en/stable/installing/
