### ISSUE TITLE
レポジトリをプルして、ブランチを切って、Pull Requestを作る

### ISSUE THREAD

**Issue by diohabara** [yuichan00/NLP100#2]
- [x] sshを設定する
- [x] repositoryをpullする
- [x] branchを新しく作る
- [x] コミットをする
- [x] pull requestを作る

**Comment by yuichan00** [comment]
sshとは
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by yuichan00** [comment]
https://backlog.com/ja/git-tutorial/stepup/07/
